project:
  type: website

website:
  navbar:
    right:
      - href: report.qmd
        text: "Home"
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/jim-franklin/intelbyte

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



