project:
  type: website
  output-dir: docs
  resources:
    - assets/**
    - images/**

website:
  favicon: favicon.ico
  navbar:
    right:
      - href: index.qmd
        text: Report
      - href: presentation.qmd
        text: Presentation
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/jim-franklin/intelbyte

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



