project:
  type: website

website:
  favicon: images/favicon.ico
  navbar:
    right:
      - href: index.qmd
        text: Report
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/jim-franklin/intelbyte

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



