name: report_intelbyte
channels:
  - conda-forge
dependencies:
  - python=3.14.2
  - pip=25.3
  - jupyterlab=4.5.1
  - ipykernel=7.1.0
  - pandas=2.3.3
  - numpy=2.3.5
  - matplotlib=3.10.8
  - plotly=6.5.0
  - scikit-learn=1.8.0
  - pyarrow=22.0.0
  - openpyxl=3.1.5
  - pyyaml=6.0.3
  - requests=2.32.5
  - altair=6.0.0